using Microsoft.EntityFrameworkCore;
using WEBASE.EF;

namespace spotify.datalayer.pgsql.EfCode;
public partial class PgSqlContext : BaseDbContext
{
    public PgSqlContext(DbContextOptions options)
            : base(options)
    { }

    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
    { }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        base.OnModelCreating(modelBuilder);
    }
}

// Scaffold-DBContext "Host=localhost;Username=postgres;Password=0803;Database=Spotify;" Npgsql.EntityFrameworkCore.PostgreSQL -DataAnnotations -OutputDir AutoGenerated -Namespace spotify.datalayer.pgsql -StartupProject spotify.datalayer.pgsql -Project spotify.datalayer.pgsql